### ISSUE TITLE
Collision shape cannot be used as a track in the animation editor

### ISSUE THREAD

**Issue by seadra** [okamstudio/godot#1045]
I have an animation which has tracks such as CollisionShape2D:shape:height. In the animation player, the height changes just fine, and I get no errors/warnings.

When I play the animation in the editor, I only get
```
ERROR: get_current_animation_pos: Condition ' !playback.current.from ' is true. returned: 0
   At: scene/animation/animation_player.cpp:1039.
```
and the height of the collision shape changes properly (I don't know what this error is supposed be).

When I start the game though, I get
```
ERROR: get_node: Node not found: CollisionShape2D:shape:height
   At: scene/main/node.cpp:828.
ERROR: _generate_node_caches: On Animation: 'stand', couldn't resolve track:  'CollisionShape2D:shape:height'
   At: scene/animation/animation_player.cpp:250.
ERROR: get_node: Node not found: CollisionShape2D:transform/pos
   At: scene/main/node.cpp:828.
ERROR: _generate_node_caches: On Animation: 'stand', couldn't resolve track:  'CollisionShape2D:transform/pos'
   At: scene/animation/animation_player.cpp:250.
ERROR: get_node: Node not found: CollisionShape2D:shape:height
   At: scene/main/node.cpp:828.
ERROR: _generate_node_caches: On Animation: 'walk', couldn't resolve track:  'CollisionShape2D:shape:height'
   At: scene/animation/animation_player.cpp:250.
ERROR: get_node: Node not found: CollisionShape2D:transform/pos
   At: scene/main/node.cpp:828.
ERROR: _generate_node_caches: On Animation: 'walk', couldn't resolve track:  'CollisionShape2D:transform/pos'
   At: scene/animation/animation_player.cpp:250.
```
and I'm not sure if the heigh/pos are changed properly (probably not).
**Edit**: confirmed, they are not changed to the proper value when the scene is run.

I'm getting this only for "sub-properties" (the ones that involve '/'), others work fine.

**Comment by reduz** [comment]
this happens because CollisionShape2D does not exist at runtime, it's just a helper to place your colliders

**Comment by seadra** [comment]
That's quite a quirk.
Can't you make it exists at runtime? Or is there a workaround

Otherwise, how are we supposed to make proper collision boxes for objects with dynamic size?
BTW, this is not an edge case at all, even Mario can crouch, halving the collision box.

**Comment by okamstudio** [comment]
will probably change it at some point to allow this, but for now you have
code access to the collision shapes via the API in CollisionObject

On Tue, Jan 6, 2015 at 7:26 AM, seadra <notifications@github.com> wrote:

> That's quite a quirk.
> Can't you make it exists at runtime? Or is there a workaround
>
> Otherwise, how are we supposed to make proper collision boxes for objects
> with dynamic size?
> BTW, this is not an edge case at all, even Mario can crouch, halving the
> collision box.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1045#issuecomment-68849272>.
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
Oh my. The collision boxes are naturally drawn in a visual editor.

The current workaround (draw the collision boxes separately, note them down, and manually set them in code) isn't practical and defeats the whole purpose of a visual animation editor and the concept of animation.

You may want to remove "animate any property" from the [advertising image on godot homepage](http://www.godotengine.org/wp/wp-content/uploads/2014/08/940x396xeditor2.jpg.pagespeed.ic.a7W9YCLkez.jpg) until this is fixed. Right now, not even being able to make a Mario is a huge frusturation :(

**Comment by okamstudio** [comment]
I'm sorry about your frustration, it must feel terrible :)
I will keep thinking about this, maybe it can be done somehow


On Sun, Jan 11, 2015 at 11:12 AM, seadra <notifications@github.com> wrote:

> Oh my. The collision boxes are naturally drawn in a visual editor.
>
> The current workaround (draw the collision boxes separately, note them
> down, and manually set them in code) isn't practical and defeats the whole
> purpose of a visual animation editor and the concept of animation.
>
> You may want to remove "animate any property" from the advertising image
> on godot homepage
> <http://www.godotengine.org/wp/wp-content/uploads/2014/08/940x396xeditor2.jpg.pagespeed.ic.a7W9YCLkez.jpg>
> until this is fixed. Right now, not even being able to make a Mario is a
> huge frusturation :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1045#issuecomment-69495711>.
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
Thanks so much!
I've been thinking about making a platformer as a side project, I'll just postpone it until then (and the tilemap editor gains something similar to tiled's [terrain tool](https://github.com/bjorn/tiled/wiki/Using-the-Terrain-Tool)).

**Comment by reduz** [comment]
that's not happening as far as i know (not from my part at last, feel free
to contribute it if you wish)
there are more chances that tiled import is implemented than that

**Comment by seadra** [comment]
Oh, sorry! Indeed, I'm confusing things.
Right, tiled import that is :)

**Comment by adolson** [comment]
Tiled import? Try this, maybe: http://www.godotengine.org/forum/viewtopic.php?f=14&t=1236

**Comment by seadra** [comment]
Since 1.2 is all about UI, I thought it's worth a shot to ping :)

**Comment by puppetmaster-** [comment]
I have used a trick in my [LudumDare] (http://ludumdare.com/compo/minild-58/?action=preview&uid=39425) game.
I designed all possible collision shapes, saved them in _ready()
```gdscript
    shapetransform = get_shape_transform(0)
    shape_ball = get_shape(0)
    shape_pad = get_shape(1)
    shape_tri = get_shape(2)
    shape_square = get_shape(3)
```
and switched them with
```gdscript
    clear_shapes()
    add_shape(shape_ball,shapetransform)
```
Animating collision shapes would be more "godot like", and add the possibilities to easy morphing. :-)

**Comment by seadra** [comment]
Is this fixed by 2580ca0?

**Comment by reduz** [comment]
yes

**Comment by reduz** [comment]
a lot of users requested this, so it's happening in the next version.
I would test it though :P

**Comment by seadra** [comment]
Hurray! Will do before closing the issue

**Comment by reduz** [comment]
It's still not a replacement for not using the internal shapes of
CollisionObject, that will have to happen in
3.0, due to requiring to break compatibility.. But for practical uses this
should be enough I hope.

**Comment by seadra** [comment]
> It's still not a replacement for not using the internal shapes of CollisionObject

???

I'm not sure I understand what this commit did (other than we can change Trigger and Opacity). The object I want to change is CollisionShape2D->Shape->RectangleShape2D->Extents, but it doesn't seem to be working.
How can I use whatever-has-changed-in-this-commit to change the size of hitbox in the animation (crouch vs standing)?

**Comment by reduz** [comment]
That should work too, how is it failing?

**Comment by seadra** [comment]
Sorry, in the tracks list the Extents track is shown as red  so I assumed it's not allowed. But when I played the animation it does seem to be working!

**Comment by reduz** [comment]
oh, what is shown as red is the tracks from the selected node/object

**Comment by seadra** [comment]
OMG, I feel terrible :)
I guess it's OK to close this issue.
I actually have a follow up suggestion about GUI/usability, but it's probably better to do it in a separate issue.
